name: cli
on:
  push:
  pull_request:
    branches:
    - master

jobs:
  basic-info:
    name: Test CLI basic info on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: building
      run: |
        npm install
        npm run build
    - name: create workspace
      run: mkdir -p myworkspace
    - name: test client basic info
      working-directory: ./myworkspace
      run: |
        ../packages/cli/dist/bin/pipcook -v
        ../packages/cli/dist/bin/pipcook --version
        ../packages/cli/dist/bin/pipcook -h
        ../packages/cli/dist/bin/pipcook --help
        ../packages/cli/dist/bin/pipcook init --help
        ../packages/cli/dist/bin/pipcook run --help
        ../packages/cli/dist/bin/pipcook plugin-dev --help
        ../packages/cli/dist/bin/pipcook bip --help
        ../packages/cli/dist/bin/pipcook serve --help

  basic-usage:
    name: Test CLI basic usage on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: building
      run: |
        npm install
        npm run build
        cd ./packages/daemon && npm start
    - name: test client basic usage init
      run: |
        ./packages/cli/dist/bin/pipcook init
    - name: test client basic usage run
      run: |
        ./packages/cli/dist/bin/pipcook run ./test/pipelines/text-bayes-classification.json
    - name: test client basic usage plugin-dev
      run: |
        ./packages/cli/dist/bin/pipcook plugin-dev -t dataCollect
