name: cli
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  testing-runs:
    name: Test Pipcook Tools main commands
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Using Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Building Pipcook
      run: |
        npm install
        npm run build
    - name: pipcook init
      env:
        NODE_ENV: local
      run: |
        ./packages/cli/dist/bin/pipcook init
        ./packages/cli/dist/bin/pipcook daemon start
    - name: install plugins from specific pipeline
      run: |
        ./packages/cli/dist/bin/pipcook pipeline install ./test/pipelines/text-bayes-classification.json
    - name: pipcook run from local filename
      run: |
        ./packages/cli/dist/bin/pipcook run ./test/pipelines/text-bayes-classification.json
    - name: pipcook plugin install
      run: |
        ./packages/cli/dist/bin/pipcook plugin install ./packages/plugins/data-collect/csv-data-collect
        ./packages/cli/dist/bin/pipcook plugin install ./packages/plugins/model-define/detectron-fasterrcnn-model-define
    - name: "pipcook plugin-dev"
      run: |
        ./packages/cli/dist/bin/pipcook plugin-dev -t dataCollect
