name: esBuild
on:
  push:
    branches:
    - master
    paths-ignore:
    - 'docker/**'
    - 'docs/**'
    - 'notebooks/**'
    - '.github/markdown.yml'
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
    - master
    paths-ignore:
    - 'docker/**'
    - 'docs/**'
    - 'notebooks/**'
    - '.github/markdown.yml'

jobs:
  universal:
    name: Build with esBuild
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Installing Pipcook
      run: |
        yarn
    - name: Building Pipcook
      run: |
        yarn dev-build
    - name: Running unit tests
      run: |
        yarn init-dev
        yarn test
