name: check markdown files
on:
  push:
    branches:
    - v1.x
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches:
    - v1.x

jobs:
  markdown-link-check:
    if: ${{ github.event_name == 'push' || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.markdown.config.json'
        folder-path: 'docs'
