name: validating user scenarios
on:
  push:
  pull_request:
    branches:
    - master

jobs:
  pipeline-user-scenario:
    name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12']
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: building
      run: |
        npm install
        npm run build
    - name: create workspace
      run: mkdir -p myworkspace
    - name: install pipcook
      working-directory: ./myworkspace
      run: |
        npm install ../packages/cli
    - name: initialize a pipeline project
      working-directory: ./myworkspace
      run: |
        mkdir -p mypipeline && cd mypipeline && ../node_modules/.bin/pipcook init
